### ISSUE TITLE
require vertx returns undefined 

### ISSUE THREAD

**Issue by nicolasembleton** [muraken720/vertx-eventbus-client#2]
Hi,

I'm facing that error:

``` javascript
$ node test/node-client.js 
./vertx-eventbus-client-master/test/node-client.js:6
var eb = new vertx.EventBus('http://localhost:8080/eventbus');
                  ^
TypeError: Cannot read property 'EventBus' of undefined
    at Object.<anonymous> (vertx-eventbus-client-master/test/node-client.js:6:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Basically, "vertx" variable is undefined as a return for "var vertx = require('vertx-eventbus-client');".

**Comment by harryjoy** [comment]
This has been resolved, now it uses `var vertx = require('../index.js');` and above error is not thrown.
